---
# defaults file for citus
citus_major_version: 9.5
citus_host_group: citus
citus_coordinator: false
citus_node_variable: ansible_hostname
# Allow unrestricted access to nodes in the local network.
citus_config: []
# citus_config takes two elements: line and state (optional)
#
# Example:
#  - citus_config:
#    - line: citus.enable_repartition_joins = true
#    - line: citus.enable_version_checks = false
#      state: absent
pg_version: 12
pg_user: postgres
pg_group: postgres
postgresql_service: postgresql
postgresql_data_path: /var/lib/postgresql
postgresql_conf_path: /etc/postgresql
postgresql_bin_path: /usr/lib/postgresql
